# Generated by Django 5.2 on 2025-04-08 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller_account', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eghamatgah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان اقامتگاه')),
                ('eghamat_type', models.CharField(choices=[('villa', 'ویلا'), ('aparteman', 'آپارتمان'), ('khanebagh', 'خانه باغ'), ('kolbe', 'کلبه')], max_length=100, verbose_name='نوع اقامتگاه')),
                ('ostan', models.CharField(max_length=20, verbose_name='استان')),
                ('shahr', models.CharField(max_length=20, verbose_name='شهر')),
                ('address', models.CharField(max_length=300, verbose_name='آدرس کامل')),
                ('tedad_otagh', models.PositiveIntegerField(null=True, verbose_name='تعداد اتاق')),
                ('zarfiat', models.PositiveIntegerField(null=True, verbose_name='ظرفیت')),
                ('gheymat_har_shab', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='قیمت هر شب')),
                ('time_voroud', models.TimeField(null=True, verbose_name='تایم ورود')),
                ('time_khorouj', models.TimeField(null=True, verbose_name='تایم خروج')),
                ('description', models.CharField(max_length=200, verbose_name='توضیحات تکمیلی')),
                ('image', models.ImageField(null=True, upload_to='media', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='seller_account.seller', verbose_name='فروشنده')),
            ],
            options={
                'verbose_name': 'مشخصات اقامتگاه',
                'verbose_name_plural': 'مشخصات اقامتگاه ها',
            },
        ),
    ]
