# Generated by Django 5.2 on 2025-04-22 08:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller_account', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eghamatgah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان اقامتگاه')),
                ('eghamat_type', models.CharField(choices=[('villa', 'ویلا'), ('aparteman', 'آپارتمان'), ('khanebagh', 'خانه باغ'), ('kolbe', 'کلبه')], max_length=100, verbose_name='نوع اقامتگاه')),
                ('ostan', models.CharField(max_length=20, verbose_name='استان')),
                ('shahr', models.CharField(max_length=20, verbose_name='شهر')),
                ('address', models.CharField(max_length=300, verbose_name='آدرس کامل')),
                ('tedad_otagh', models.PositiveIntegerField(null=True, verbose_name='تعداد اتاق')),
                ('metrazh', models.PositiveIntegerField(null=True, verbose_name='متراژ')),
                ('zarfiat', models.PositiveIntegerField(null=True, verbose_name='ظرفیت')),
                ('zarfiat_extra', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تعداد نفرات اضافه')),
                ('gheymat_har_shab', models.IntegerField(null=True, verbose_name='قیمت هر شب')),
                ('time_voroud', models.TimeField(null=True, verbose_name='تایم ورود')),
                ('time_khorouj', models.TimeField(null=True, verbose_name='تایم خروج')),
                ('description', models.CharField(max_length=200, verbose_name='توضیحات تکمیلی')),
                ('wifi', models.BooleanField(default=False, verbose_name='اینترنت وای فای')),
                ('parking', models.BooleanField(default=False, verbose_name='پارکینگ')),
                ('pool', models.BooleanField(default=False, verbose_name='استخر')),
                ('kitchen', models.BooleanField(default=False, verbose_name='آشپزخانه')),
                ('tv', models.BooleanField(default=False, verbose_name='تلویزیون')),
                ('image', models.ImageField(default='', upload_to='media', verbose_name='تصویر1')),
                ('image2', models.ImageField(default='', upload_to='media', verbose_name='تصویر2')),
                ('image3', models.ImageField(default='', upload_to='media', verbose_name='تصویر3')),
                ('image4', models.ImageField(default='', upload_to='media', verbose_name='تصویر4')),
                ('image5', models.ImageField(default='', upload_to='media', verbose_name='تصویر5')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])], verbose_name='ویدیو')),
                ('aparat_video_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='seller_account.seller', verbose_name='فروشنده')),
            ],
            options={
                'verbose_name': 'مشخصات اقامتگاه',
                'verbose_name_plural': 'مشخصات اقامتگاه ها',
            },
        ),
        migrations.CreateModel(
            name='EghamatComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('star', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=20, verbose_name='امتیاز')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentcomment', to='eghamatgah.eghamatcomment', verbose_name='والد')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('eghamat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eghamatgah.eghamatgah', verbose_name='اقامتگاه')),
            ],
            options={
                'verbose_name': 'نظر اقامتگاه',
                'verbose_name_plural': 'نظرات اقامتگاه',
            },
        ),
        migrations.CreateModel(
            name='AvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت روز')),
                ('eghamat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_dates', to='eghamatgah.eghamatgah')),
            ],
            options={
                'verbose_name': 'بازه تاریخ قابل رزرو',
                'verbose_name_plural': 'بازه های تاریخ\u200cهای قابل رزرو',
            },
        ),
        migrations.CreateModel(
            name='Eghamatgah_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان دسته بندی')),
                ('url_title', models.CharField(max_length=200, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parenteghamatcategory', to='eghamatgah.eghamatgah_category', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name': 'دسته بندی اقامتگاه',
                'verbose_name_plural': 'دسته بندی های اقامتگاه ها',
            },
        ),
        migrations.AddField(
            model_name='eghamatgah',
            name='Ecategory',
            field=models.ManyToManyField(blank=True, related_name='categories', to='eghamatgah.eghamatgah_category', verbose_name='دسته بندی'),
        ),
        migrations.CreateModel(
            name='UnavailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('eghamat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_dates', to='eghamatgah.eghamatgah')),
            ],
        ),
    ]
