# Generated by Django 5.2 on 2025-04-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eghamatgah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eghamatgah',
            name='image',
            field=models.ImageField(default='', upload_to='media', verbose_name='تصویر'),
        ),
    ]
