# Generated by Django 5.2 on 2025-04-27 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
        ('eghamatgah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eghamatcomment',
            name='booking',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking', verbose_name='رزرو مربوطه'),
        ),
    ]
