# Generated by Django 5.2 on 2025-04-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eghamatgah', '0002_alter_eghamatgah_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eghamatgah',
            name='gheymat_har_shab',
            field=models.IntegerField(null=True, verbose_name='قیمت هر شب'),
        ),
    ]
