# Generated by Django 5.2 on 2025-04-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eghamatgah', '0003_alter_eghamatgah_gheymat_har_shab'),
    ]

    operations = [
        migrations.AddField(
            model_name='eghamatgah',
            name='kitchen',
            field=models.BooleanField(default=False, verbose_name='آشپزخانه'),
        ),
        migrations.AddField(
            model_name='eghamatgah',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='پارکینگ'),
        ),
        migrations.AddField(
            model_name='eghamatgah',
            name='pool',
            field=models.BooleanField(default=False, verbose_name='استخر'),
        ),
        migrations.AddField(
            model_name='eghamatgah',
            name='tv',
            field=models.BooleanField(default=False, verbose_name='تلویزیون'),
        ),
        migrations.AddField(
            model_name='eghamatgah',
            name='wifi',
            field=models.BooleanField(default=False, verbose_name='اینترنت وای فای'),
        ),
    ]
