# Generated by Django 5.2 on 2025-04-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eghamatgah', '0004_eghamatgah_kitchen_eghamatgah_parking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eghamatgah',
            name='metrazh',
            field=models.PositiveIntegerField(null=True, verbose_name='متراژ'),
        ),
    ]
