# Generated by Django 5.2 on 2025-04-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eghamatgah', '0006_eghamatcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='eghamatcomment',
            name='star',
            field=models.BooleanField(default=False, verbose_name='امتیاز'),
        ),
    ]
