# Generated by Django 5.2 on 2025-04-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eghamatgah', '0007_eghamatcomment_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eghamatcomment',
            name='star',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=20, verbose_name='امتیاز'),
        ),
    ]
