# Generated by Django 5.2 on 2025-04-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(blank=True, null=True, verbose_name='تاریخ ورود')),
                ('check_out', models.DateField(blank=True, null=True, verbose_name='تاریخ خروج')),
                ('persons', models.PositiveIntegerField(verbose_name='تعداد نفرات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'همه رزروها',
            },
        ),
    ]
