# Generated by Django 5.2 on 2025-04-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20, null=True, verbose_name='نام شرکت/کمپانی')),
                ('phone_number', models.CharField(max_length=50, null=True, verbose_name='تلفن همراه')),
            ],
        ),
    ]
