# Generated by Django 5.2 on 2025-04-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='نام کمپانی')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='شماره تماس')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین /غیر ادمین')),
            ],
            options={
                'verbose_name': 'فروشنده',
                'verbose_name_plural': 'فروشندگان',
            },
        ),
    ]
