# Generated by Django 5.2 on 2025-04-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_account', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='user',
        ),
    ]
