# Generated by Django 5.2 on 2025-04-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_account', '0003_remove_seller_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'فروشنده', 'verbose_name_plural': 'فروشندگان'},
        ),
        migrations.AddField(
            model_name='seller',
            name='name',
            field=models.CharField(max_length=300, null=True, verbose_name='نام و نام خانوداگی'),
        ),
    ]
